settings:
  application:
    name: go-project
    mode: dev
    host: localhost
    port: 8000
    read_timeout: 60
    write_timeout: 60
    version: "v0.0.1"
    start_time: "2024-07-24"
    machine_id: 1
  self:
    INTERNAL_API_KEY: ""
  log:
    level: "info"
    filename: "web_app.log"
    max_size: 200
    max_age: 30
    max_backups: 7
  verctorDB:
    url: ""
    key: ""
    username: ""
    database_name: ""
    site_collection_view: ""
    knowledge_base_collection_view: ""
  redis:
    host: localhost
    port: 6379
    password: # 空
    default_DB: 0
    dial_timeout: 5s
